### ISSUE TITLE
wrong styles for HTML view

### ISSUE THREAD

**Issue by maacaron** [FelipeMartinin/frozen#3]
Hi,
something wrong is with HTML view in Chrome 45.0.2454.85 m.
![frozen](https://cloud.githubusercontent.com/assets/5049531/9810714/dcdc36d6-5872-11e5-97f0-7421af45ecbc.JPG)
Could you check that?

**Comment by FelipeMartinin** [comment]
Hi maaracon. Thanks for the notification and excuse my delay

Google changed some things in the devtools that broke my theme. I'll fix it as soon as possible!

**Comment by FelipeMartinin** [comment]
At this moment I'm woking in a 3.0 version with a lot of features! I intend to release it till the end of this month.

**Comment by FelipeMartinin** [comment]
Version 3 of this theme was released today and all issues was fixed. Enjoy it! :D
